# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: keypop-theme
  theme_night:
  font: 'keypop-font'
  font_size: M

# SEO

marketing:
  seo:
    site_type: Project
    local_business_type: ''
    org_name: 'Eclipse'
    description: 'Eclipse Keypop® accelerates the development through a universal, open and modular platform that provides high-level APIs and ensures application reliability and compliance.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: 'GTM-5WLCZXC'
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: c
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '&copy; 2023-{year} The Eclipse Keypop® project. All Rights Reserved.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: '2006-01-02'
  time_format: '15:04'
  address_format: en-us

# Site features
features:
  syntax_highlighter:
    enable: true
    theme_light: github-dark
    theme_dark: github-dark
    extra_languages:
      - java
      - groovy
      - xml
      - kotlin
      - cpp
      - gradle
      - ini
      - make
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/eclipse-keypop/keypop-website'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Custom JS extension
plugins_js: ['custom']

# Custom variables
keypop_api_version:
  keypop_reader_java_api: '2.1.0'
  keypop_card_java_api: '2.0.1'
  keypop_calypso_card_java_api: '2.2.0'
  keypop_calypso_crypto_symmetric_java_api: '0.1.1'
  keypop_calypso_crypto_legacysam_java_api: '1.0.0'
  keypop_calypso_crypto_asymmetric_java_api: '0.2.0'
  keypop_storagecard_java_api: '1.1.1'

  keypop_reader_cpp_api: '2.0.0'
  keypop_card_cpp_api: '2.0.0'
  keypop_calypso_card_cpp_api: '2.0.0'
  keypop_calypso_crypto_symmetric_cpp_api: '0.1.0'
  keypop_calypso_crypto_legacysam_cpp_api: '0.6.0'
  keypop_calypso_crypto_asymmetric_cpp_api: '0.2.0'
